README.md
gitly.v
release.v
repo.v
repo_db.v
tag.v
templates/releases.html
user.v

releases.html still needs to be updated, but
this is an intermediate step necessary for
that to be updated properly.

add tags and releases to database

---

gitly.v
release.v
repo_db.v
tag.v
templates/releases.html

Still a problem with getting and printing correct user, need to figure out other ORM stuff for that.

releases page almost works again

---

gitly.v
templates/contributors.html

i fixed the contributors layout which was broken by the .user css rule

fix contributors layout

---

static/css/files.scss
static/css/gitly.css
static/css/gitly.scss

* also fixed line height and removed some hacks for that

Use native font stack

---

branch.v
gitly.v
oauth.v
tag.v

remove extra sorts since orm order update

---

git.v
oauth.v

This PR fixes compilation with V 0.1.28 2284865

Fix compilation with latest v

---

.github/workflows/ci.yml
admin.v
api.v
cli.v
comment.v
commit.v
file.v
gitly.v
hl/hl.v
issue.v
login.v
oauth.v
repo.v
repo_db.v
settings.v
token.v
user.v
usersite.v
visit.v

With this `v .` compiles gitly without any warnings.

Fixes for clean compilation (no warnings) with V 0.1.29 d34c5b7

---

gitly.v
templates/user/settings.html
usersite.v

fixed gitly for new vweb

---

gitly.v
repo.v
repo_db.v
usersite.v

Fix issues

---

README.md

Added curl example to download CSS file

Added curl example to download CSS file

---

gitly.v
login.v
usersite.v

fixes the user icon if the user has no avatar

fix user icons

---

oauth.v

Accompanying V PR: https://github.com/vlang/v/pull/9462

Use enum instead of string for .add_header signature change

---

admin.v
gitly.v
login.v
repo_db.v
settings.v
templates/admin/settings.html
templates/header.html
templates/new.html

this pr adds a hostname settings, makes the first user, who registers an admin and add a path to tree and blobs inside repos

add hostname, make first user admin, add inside repo path

---

login.v

Should fix failing tests at vlang/v

login: update for vlang/v#13570

---

login.v

Necessary for [PR #14212](https://github.com/vlang/v/pull/14212)

fix use of reserved type name in `for in` stmt

---

templates/index.html

fix styles and closing tags

---

git/network.v
git_routes.v
git_service.v

Push is available, but no access control, update the copy in Gitly and other stuff, but push is available. 🎉

feature: push

---

git/branch.v
repo_routes.v
repo_service.v
user_service.v

Temporary removed parallel tasks for better development experience while we migrate to Postgres. Now all actions perform smoothly and without errors.

fix: clone and concurrent tasks

---

commit_routes.v
repo_service.v
templates/commit.html

As GitHub can: [patch](https://github.com/vlang/gitly/commit/0847914b08fdb82008837d74f5537676ac0e27df.patch)

feature: read patches

---

lang_stats_service.v
repo_service.v

Now it works with git ls-tree not a working tree.

fix: lang stats

---

repo_routes.v
static/css/gitly.scss
static/css/main.scss
static/css/new.scss
templates/new.html
templates/user/repos.html

feature: repository description, repository visibility

---

static/css/files.scss
templates/tree.html

feature: last commit message

---

file_template.v
static/css/files.scss
static/css/tree.scss
templates/tree.html

feature: highlight issue id

---

repo_routes.v
repo_service.v
static/css/langs.scss
static/css/tree.scss
templates/header.html
templates/tree.html

feature: about repository

---

.gitignore
branch_service.v
gitly.v
release_entities.v
release_routes.v
release_service.v
repo_routes.v
repo_service.v
repo_template.v
settings_entities.v
static/css/gitly.scss
static/css/releases.scss
tag_entities.v
tag_routes.v
tag_service.v
templates/releases.html
utils.v
validation/validation_service.v

feature: releases

---

static/css/gitly.scss
templates/header.html
tests/first_run.v

feature: repository visibility tag

---

static/css/gitly.scss
templates/login.html
templates/new.html
templates/register.html
templates/user/settings.html

feature: form styles

---

activity_entities.v
activity_service.v
gitly.v
static/css/user.scss
templates/user.html
user_entities.v
user_routes.v
user_service.v

feature: activities

---

ssh_key_entities.v
ssh_key_routes.v
ssh_key_service.v
static/css/gitly.scss
static/css/user.scss
templates/user/settings.html
templates/user/ssh/keys/list.html
templates/user/ssh/keys/new.html
tests/first_run.v
user_entities.v
user_routes.v

feature: manage ssh keys

---

src/git_routes.v

Now you can clone large git repos, for example, v from https://gitly.org/alex/v

feature: gzip support

---

src/security_log_service.v

Needed for https://github.com/vlang/v/pull/15932

security_log_service: add `unsafe` block to int -> enum cast

---

api/api.v
src/api_routes.v
src/gitly.v
src/repo_routes.v
src/repo_service.v
src/star_entities.v
src/star_service.v
src/static/css/tree.scss
src/templates/header.html
src/templates/tree.html
src/templates/user/stars.html

feature: stars

---

src/repo_routes.v
src/templates/repo/settings.html

This pullrequest changes the DELETE endpoint /:user/:repo to the POST endpoint /:user/:repo/delete.
This pullrequest also changes the html matching the endpoint changes.
**TL;DR it works now**
I tested it locally.

Fix #204 deletion of repositories

---

src/templates/blob.html
src/templates/commit.html

fix: preview paddings

---

src/crypto.v

Needed for https://github.com/vlang/v/pull/16332

crypto: update const type

---

src/templates/admin/settings.html
src/templates/issue.html
src/templates/login.html
src/templates/new.html
src/templates/new/issue.html
src/templates/register.html
src/templates/user/settings.html
src/templates/user/ssh/keys/new.html

feature: disable the submit button after submitting

---

src/static/css/gitly.scss
src/templates/footer.html

feature: alerts

---

src/branch_service.v
src/feed_entities.v
src/feed_service.v
src/gitly.v
src/repo_routes.v
src/static/css/feed.scss
src/static/css/gitly.scss
src/static/css/tree.scss
src/templates/header.html
src/templates/tree.html
src/templates/user/feed.html
src/watch_entities.v
src/watch_service.v
tests/first_run.v

feature: feed

---

api/api.v
src/file_service.v
src/gitly.v
src/repo_routes.v
src/repo_service.v
src/templates/blob.html
src/templates/layout/tree_path.html
src/templates/tree.html

feature: pretty_size, path, loc for blobs.

---

git/libgit.v

for green CIs:
https://github.com/vlang/v/pull/19944

set `nil` as the initial value of the struct reference type fields

---

src/repo.v

sorry :(
I missed one.
for green CI:
https://github.com/vlang/v/actions/runs/6927788739/job/18868127321?pr=19944

set nil as the initial value of the struct reference type fields(part 2)

---

api/api.v

Required for https://github.com/vlang/v/pull/21183

add `pub` access modifier to publicly used struct fields

---

highlight/java.v
highlight/langs.v

highlight: add support for java
